
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

## Prerequsites 

```{r}
library(sf)
library(tidyverse)
library(terra)
```

```{r}
# practice filtering a raster
elev <- rast(nrow = 6, ncol = 6, resolution = 0.5,
             xmin = -1.5, xmax = 1.5, ymin = -1.5, ymax = 1.5,
             vals = 1:36)
plot(elev)
```

```{r}
# set all cells to NA based on condition
elev[elev < 20] <- NA
plot(elev)
```

```{r}
# let's practice combining (or unioning) geometries
# read in shapefile of the counties of North Carolina

nc = st_read(system.file("shape/nc.shp", package = 'sf'))
plot(nc["AREA"])
```

```{r}
# combines all geometries without resolving borders
nc_combine = st_combine(nc)
plot(nc_combine) # still has boarders, but its now one big multipolygon
```

```{r}
# finds the union of all geometries
nc_union = st_union(nc)
plot(nc_union) # multipolygon, but dissolves county borders; does not keep those geometry data
```

```{r}
# let's exploring removing geometries
# pick a few counties to remove
counties = nc %>%
  filter(NAME %in% c("Ashe", "Alleghany", "Surry")) %>% # takes counties and combines those geometries into multipolygon, dissolving borders
  st_union()
plot(counties)
```

```{r}
# plot counties on top of the unioned version of NC
ggplot() +
  geom_sf(data = nc_union, fill = "grey", color = 'transparent') +
  geom_sf(data = counties, fill = "black", color = 'transparent') +
  theme_void()
```

```{r}
# create a new geometry that is the difference between the unioned version of NC and the counties
nc_difference = st_difference(nc_union, counties)
nc_disjoint = st_disjoint(nc_union, counties) # empty polygon bc there are no parts of the counties that don't touch nc
nc_intersection = st_intersection(nc_union, counties)
```

```{r}
# plot the difference on top of the unioned version of NC
# counties should be missing!
ggplot() +
  geom_sf(data = nc_difference, fill = "grey") +
  geom_sf(data = nc_intersection, fill = "black") +
  theme_void()
```
